# Generated by Django 4.2.11 on 2024-06-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='num_guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='num_persons',
            field=models.PositiveIntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='reservation.table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default='2'),
        ),
    ]
